apiVersion: v2
name: eso
description: A Helm chart for External Secrets Operator
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: external-secrets
  repository: https://charts.external-secrets.io
  version: 0.20.1
