apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:qwy86645/kardio.git
    targetRevision: HEAD
    path: apps/fluent-bit
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
