apiVersion: v2
name: loki
description: A Helm chart for loki
type: application
version: 0.1.1
appVersion: "0.1.1"
dependencies:
- name: loki-stack
  repository: https://grafana.github.io/helm-charts
  version: 2.10.2
  # alias: app
