apiVersion: v2
name: loki
description: A Helm chart for loki
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: loki
  repository: https://grafana.github.io/helm-charts
  version: 6.40.0
  alias: app
