loki-stack:
  loki:
    enabled: true
    image:
      tag: 2.9.3
    persistence:
      enabled: false
    service:
      type: ClusterIP

  grafana:
    enabled: true
    service:
      type: ClusterIP
    persistence:
      enabled: false
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard

  promtail:
    enabled: false

  #   config:
  #     clients:
  #     - url: http://dawn-loki:3100/loki/api/v1/push
