apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kardio
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:qwy86645/kardio.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{path[1]}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "kardio"
      source:
        repoURL: git@github.com:qwy86645/kardio.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}-kardio"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
